# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Teste',
                'doc_host': 'https://thaleshqs.github.io',
                'git_url': 'https://github.com/thaleshqs/Teste',
                'lib_path': 'Teste'},
  'syms': {'Teste.core': {'Teste.core.foo': ('core.html#foo', 'Teste/core.py')}}}
